# Generated by Django 3.2.7 on 2021-10-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredienst',
            new_name='ingredients',
        ),
    ]
